#pragma once
const char *help_text =
	"Usage: texpack -o <output-files-prefix> [options...] [<input-file>]\n"
	"\n"
	"The <input-file> should contain a list of image files (png) separated by new\n"
	"lines. If no <input-file> is given, it will read from stdin.\n"
	"\n"
	"Options:\n"
	"\n"
	"-h, --help            Show this help.\n"
	"-o, --output          Prefix for the generated files (atlas and json).\n"
	"-p, --padding         Padding between sprites.\n"
	"-s, --size            Fixed size for the atlas image (i.e. 512x512).\n"
	"-S, --max-size        Treat size parameter as maximum size.\n"
	"-P, --POT             Keep atlas size a power of two (ignored if size is used).\n"
	"-r, --allow-rotate    Allows sprites to be rotated for better packing.\n"
	"-m, --metadata        Input metadata file in json format. (*)\n"
	"-e, --pretty          Generated json file will be human readable.\n"
	"-t, --trim            Trim input images.\n"
	"-i, --indentation     Number of spaces for indentation, 0 to use tabs (default).\n"
	"-u, --premultiplied   Atlas images will have premultiplied alpha.\n"
	"-b, --alpha-bleeding  Post-process atlas image with an alpha bleeding algorithm.\n"
	"-M, --mode            Specifies the packing heuristic. Allowed values are:\n"
	"                        * auto (default; tries all modes and selects one)\n"
	"                        * bottom-left\n"
	"                        * short-side\n"
	"                        * long-side\n"
	"                        * best-area\n"
	"                        * contact-point\n"
	"-f, --format          Specifies the output format of the JSON file. Values are:\n"
	"                        * legacy (default; uses the original JSON format created by urraka)\n"
	"                        * jsonhash (Texture Atlas JSON Hash format)\n"
	"                        * jsonarray (Texture Atlas JSON Array format)\n"
	"                        * xml (Texture Atlas XML)\n"
	"\n"
	"(*) The format of the metadata file should be as follows:\n"
	"\n"
	"    {\n"
	"      \".global\": {\"param\": \"value\", ...},\n"
	"      \"someimage.png\":    {\"param1\": \"some-value\", \"param2\": 0, ...},\n"
	"      \"anotherimage.png\": \"not necessarily an object\",\n"
	"      ...\n"
	"    }\n"
	"\n"
	"    Each file name should match one in the <input-file> list. The \".global\" file\n"
	"    name is used for global metadata.\n"
	"";
